//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema02_MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class employee
    {
        public int id { get; set; }
        [DisplayName("NOMBRE COMPLETO")]
        public string nombre { get; set; }
        [DisplayName("DIRECCIÓN")]
        public string direccion { get; set; }
        [DisplayName("TELÉFONO")]
        public string telefono { get; set; }
        [DisplayName("DEPARTAMENTO")]
        public int deparment_id { get; set; }
    
        public virtual deparment deparment { get; set; }
    }
}
